
services:
    Arthem\Bundle\CoreBundle\Form\GoogleAutoCompleteType:
        arguments:
            - ~ # Google API key
        tags:
            - { name: form.type }

    Arthem\Bundle\CoreBundle\Form\AddressAutoCompleteType:
        parent: "Arthem\\Bundle\\CoreBundle\\Form\\GoogleAutoCompleteType"
        tags:
            - { name: form.type }
