services:
    _defaults:
        autowire: true
        autoconfigure: true

    Arthem\Bundle\CoreBundle\Command\SendEmailCommand:
        tags:
            - { name: 'console.command', command: 'arthem:mailer:send' }
